# This file was created with the help of the GitHub Actions workflow for deploying to Firebase Hosting on merges.
# It uses the Firebase Extended action to deploy the site to Firebase Hosting when a merge is made
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FONDATION_TAFI_CAMEROUN }}
          channelId: live
          projectId: fondation-tafi-cameroun
